base-execution:
  image: nethermindeth/nethermind:latest
  entrypoint: ["/snapshot-download.sh"]
  command: ["--config", "base"]
  environment:
    - NETHERMIND_L1_RPC_URL=http://192.168.7.17:8545
    - NETHERMIND_L1_BEACON_URL=http://192.168.7.18:5052
    - JsonRpc.Enabled=true
    - JsonRpc.Host=0.0.0.0
    - JsonRpc.Port=8545
    - JsonRpc.CorsOrigins=*
    - JsonRpc.EnabledModules=eth,net,web3,debug,optimism
    - Optimism.Enabled=true
    - Optimism.SequencerUrl=https://mainnet-sequencer.base.org
    - Database.Path=/data
    - Sync.Snap=true
    - Network.DiscoveryPort=30304
    - Network.P2PPort=30304
  volumes:
    - base_execution_data:/data
    - snapshot_script_volume:/snapshot-download.sh:ro   # ← UNIQUE VOLUME
  networks:
    - default
  ports:
    - "8547:8545"
    - "30304:30304"
    - "30304:30304/udp"
    - "7303:6060"
  restart: unless-stopped

# === ADD THIS VOLUME ===
volumes:
  base_op_node_data:
  base_execution_data:
  snapshot_script_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/snapshot-download.sh   # ← ABSOLUTE PATH TO FILE
